import Add from "./Add"
import AddCircleOutline from "./AddCircleOutline"
import ArrowBackOutline from "./ArrowBackOutline"
import Background from "./Background"
import Compress from "./Compress"
import Customize from "./Customize"
import Elements from "./Elements"
import Expand from "./Expand"
import Graphics from "./Graphics"
import Images from "./Images"
import InformationCircleOutline from "./InformationCircleOutline"
import Layers from "./Layers"
import Logo from "./Logo"
import Pixabay from "./Pixabay"
import Redo from "./Redo"
import Search from "./Search"
import Text from "./Text"
import Templates from "./Templates"
import Undo from "./Undo"
import Refresh from "./Refresh"
import TimePast from "./TimePast"
import RemoveCircleOutline from "./RemoveCircleOutline"
import SwapHorizontal from "./SwapHorizontal"
import Underline from "./Underline"
import Uploads from "./Uploads"
import Video from "./Video"
class Icons {
  static Background = Background
  static Elements = Elements
  static Text = Text
  static Templates = Templates
  static Search = Search
  static Images = Images
  static Videos = Video
  static Graphics = Graphics
  static Pixabay = Pixabay
  static Uploads = Uploads
  static Logo = Logo
  static Compress = Compress
  static Expand = Expand
  static Undo = Undo
  static Redo = Redo
  static Refresh = Refresh
  static Layers = Layers
  static TimePast = TimePast
  static AddCircleOutline = AddCircleOutline
  static RemoveCircleOutline = RemoveCircleOutline
  static InformationCircleOutline = InformationCircleOutline
  static Customize = Customize
  static SwapHorizontal = SwapHorizontal
  static ArrowBackOutline = ArrowBackOutline
  static Underline = Underline
  static Add = Add
}

export default Icons
